### ISSUE TITLE
[deploy] Fix "Serve as a Github page"

### ISSUE THREAD

**Issue by mk-emeks** [emeks-studio/sensum#80]
So far we have:

at `.github/workflows/auto-release.yml`
```yaml
    - name: Serve as a Github page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          folder: ./sensum-pwa/dist
          branch: main
          repository-name: emeks-studio/dsensum
          token: ${{ secrets.DEPLOY_PAT }}
          git-config-name: mk-emeks
          git-config-email: mirko@emeks.com.ar
```

at `sensum-pwa/vite.config.js`:
```js

      strategies: 'injectManifest', // Vs generateSW (more out of the box, less customizable!)
      registerType: 'autoUpdate', // Vs Prompt for new content
      srcDir: 'src',
      base: '/dsensum/',
      filename: 'ServiceWorker.js',
      manifest: {
        name: 'd-sensum',
        short_name: 'd-sensum',
        display_override: ["fullscreen", "minimal-ui"],
        display: "standalone", // https://developer.mozilla.org/en-US/docs/Web/Manifest/display_override#values
        start_url: '/',
        start_url: '/dsensum/',
        description: 'mysterious app',
        theme_color: '#4B3968',
        background_color: '#4B3968',
```

Resulted repo: https://github.com/emeks-studio/dsensum
page at: https://github.com/emeks-studio/dsensum

error on console:
```
GET
https://emeks-studio.github.io/assets/index-0XwJlK10.js

GET
https://emeks-studio.github.io/assets/index-t5wgblVp.css
[HTTP/2 404  22ms]

Loading failed for the module with source “https://emeks-studio.github.io/assets/index-0XwJlK10.js”. [dsensum:13:70](https://emeks-studio.github.io/dsensum/)
GET
https://emeks-studio.github.io/assets/img/apple-touch-icon.png
[HTTP/2 404  13ms]

GET
https://emeks-studio.github.io/assets/img/favicon.svg
[HTTP/2 404  15ms]
```
